site_name: Intro to Keeling
repo_url: https://github.com/cybergis/intro-to-keeling
theme:
    name: material
    features:
        - navigation.instant
        - search.highlight
nav: 
  - Home: index.md
  - "SSH and Terminal Basics": ssh-terminal.md
  - "SLURM 101": slurm101.md
  - "Installing and Using Anaconda": conda.md
  - "Managing Data on Keeling": data.md
  - "Concepts, Resources, and FAQ": faq-resources.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences